### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by Donaldgljh** [tingwei628/rollup-plugin-hotreload#23]
[!] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at getCopyStrPaths (D:\graphApp\node_modules\rollup-plugin-hotreload\lib\helpers.js:72:36)
    at Object.e.rph (D:\graphApp\node_modules\rollup-plugin-hotreload\lib\rollup-plugin-hotreload.js:62:15)
    at Object.<anonymous> (D:\graphApp\rollup.config.js:104:29)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.require.extensions.(anonymous function) [as .js] (D:\graphApp\node_modules\rollup\dist\shared\loadConfigFile.js:508:20)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by tingwei628** [comment]
Thanks for reporting and i will take time to fix it. :)

**Comment by tingwei628** [comment]
Try update to @2.3.1
